### PR TITLE
Change metapost to web2c, change build commands

### PR DESCRIPTION
**Pull request by jakobjakobson13**

### CODE REVIEW

**Comment by fedelibre** [comment]
@jakobjakobson13 Sorry for the late reply, I didn't get any notification about this PR...

I see that the Build script has a `--prefix=$TL_INSTALL_DEST`. So I tried prepending `TL_INSTALL_DEST=/app ./Build ...` to the command. But it seems that this breaks something, because then lilypond can't find packages which are already defined (such as guile and python2). Cannot include variables in the command?!?

**Comment by jakobjakobson13** [comment]
> @jakobjakobson13 Sorry for the late reply, I didn't get any notification about this PR...

No problem, I'm busy with other stuff as well. But at least './Build --prefix=/app --without-x --disable-xetex --disable-xindy' allows to to compile a minimal version, however I have not tested it so far.

**Comment by fedelibre** [comment]
I've tested it now and doesn't work.
However, looking at the terminal output I see that binaries are placed in a arch-specific subdir of /app/bin, which I guess it's not a good thing:

```
make[6]: Entering directory '/run/build/web2c/Work/texk/web2c'
 /usr/bin/mkdir -p '/app/bin/x86_64-pc-linux-gnu'
 STRIPPROG='strip' /bin/sh ./libtool   --mode=install /bin/sh /run/build/web2c/build-aux/install-sh -c -s tangle ctangle bibtex dvicopy dvitype gftodvi gftopk gftype mft patgen pktogf pktype pltotf pooltype tftopl vftovp vptovf weave ctie cweave ctwill ctwill-refsort ctwill-twinx tie tex mf mf-nowin mflua mfluajit mpost pmpost upmpost ptex pbibtex pdvitype ppltotf ptftopl eptex uptex upbibtex updvitype uppltotf uptftopl euptex pdftex ttf2afm pdftosrc luatex luajittex odvicopy odvitype otangle wofm2opl wopl2ofm wovf2ovp wovp2ovf aleph synctex '/app/bin/x86_64-pc-linux-gnu'
```

and also:

```
make[6]: Entering directory '/run/build/web2c/Work/texk/kpathsea'
 /usr/bin/mkdir -p '/app/lib/x86_64-pc-linux-gnu'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c -s  libkpathsea.la '/app/lib/x86_64-pc-linux-gnu'
libtool: install: /usr/bin/install -c .libs/libkpathsea.lai /app/lib/x86_64-pc-linux-gnu/libkpathsea.la
libtool: install: /usr/bin/install -c .libs/libkpathsea.a /app/lib/x86_64-pc-linux-gnu/libkpathsea.a
libtool: install: strip --strip-debug /app/lib/x86_64-pc-linux-gnu/libkpathsea.a
libtool: install: chmod 644 /app/lib/x86_64-pc-linux-gnu/libkpathsea.a
libtool: install: ranlib /app/lib/x86_64-pc-linux-gnu/libkpathsea.a
libtool: finish: PATH="/app/bin:/usr/bin:/sbin" ldconfig -n /app/lib/x86_64-pc-linux-gnu
----------------------------------------------------------------------
Libraries have been installed in:
   /app/lib/x86_64-pc-linux-gnu

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/app/bin/x86_64-pc-linux-gnu'
 STRIPPROG='strip' /bin/sh ./libtool   --mode=install /bin/sh /run/build/web2c/build-aux/install-sh -c -s kpseaccess kpsereadlink kpsestat kpsewhich '/app/bin/x86_64-pc-linux-gnu'
libtool: install: /bin/sh /run/build/web2c/build-aux/install-sh -c -s kpseaccess /app/bin/x86_64-pc-linux-gnu/kpseaccess
libtool: install: /bin/sh /run/build/web2c/build-aux/install-sh -c -s kpsereadlink /app/bin/x86_64-pc-linux-gnu/kpsereadlink
libtool: install: /bin/sh /run/build/web2c/build-aux/install-sh -c -s kpsestat /app/bin/x86_64-pc-linux-gnu/kpsestat
libtool: install: /bin/sh /run/build/web2c/build-aux/install-sh -c -s kpsewhich /app/bin/x86_64-pc-linux-gnu/kpsewhich
for dir in "/app/bin/x86_64-pc-linux-gnu" "/app/lib/x86_64-pc-linux-gnu" "/app/texmf-dist/web2c" "/app/texmf-dist/web2c" "/app/lib/x86_64-pc-linux-gnu/pkgconfig" "/app/include/kpathsea" "/app/include/kpathsea"; do \
  test -z "$dir" || /usr/bin/mkdir -p "$dir"; \
done
```

I might try adding `--bindir=/app`.
Next Monday...

**Comment by fedelibre** [comment]
Correct option should be `--bindir=/app/bin`.
And lilypond configure is now almost fine:

> ERROR: Please install required programs:  metapost CTAN package (texlive-metapost)

I wonder if the error is correct. Isn't mpost binary enough?
I will ask LilyPond developers this and another question about ghostscript...

**Comment by fedelibre** [comment]
Above error is triggered by [this check in aclocal.m4 file](http://git.savannah.gnu.org/cgit/lilypond.git/tree/aclocal.m4#n1209).

So the problem is that `kpsewhich -format=mp mfplain` does not return anything. In fact, I've checked the texmf-dist directory within the builddir/files and `texmf-dist/metafont` is missing.

I've added the --datarootdir option, so kpsewhich can find the location of the directory (if unset, it will be created at the root where kpsewhich won't look up).  Current build command is:

```
build-commands:
  - ./Build --prefix=/app --bindir=/app/bin --datarootdir=/app/share --without-x --disable-xetex --disable-xindy
```

However, we must figure out how to build the `texmf-dist/metapost` directory with all the needed files.

Also, I wonder if there's a way to speed up the compilation.  This Texlive module is taking too much time. Fixing errors by trial&error is tedious and long.

**Comment by fedelibre** [comment]
We may skip the check by defining the env variable for the lilypond module:

```
build-options:
  env:
    MFPLAIN_MP: /app/share/texmf-dist
```

This allows to pass the configure step. BTW, it seems setpmake is not a requirement:

    checking for stepmake... ./stepmake  (${datarootdir}/stepmake not found)


then we reach the make step, but of course we get into trouble:

```
This is METAFONT, Version 2.7182818 (TeX Live 2019) (preloaded base=mf)

kpathsea: Running mktexfmt mf.base
Can't locate mktexlsr.pl in @INC (@INC contains: //tlpkg //texmf-dist/scripts/texlive /usr/lib/perl5/site_perl/5.30.0/x86_64-linux /usr/lib/perl5/site_perl/5.30.0 /usr/lib/perl5/vendor_perl/5.30.0/x86_64-linux /usr/lib/perl5/vendor_perl/5.30.0 /usr/lib/perl5/5.30.0/x86_64-linux /usr/lib/perl5/5.30.0) at /app/bin/mktexfmt line 23.
BEGIN failed--compilation aborted at /app/bin/mktexfmt line 25.
I can't find the base file `mf.base'!
make[1]: *** [/run/build/lilypond/stepmake/stepmake/metafont-rules.make:11: out/feta13.tfm] Error 1
make[1]: Leaving directory '/run/build/lilypond/mf'
make: *** [/run/build/lilypond/stepmake/stepmake/generic-targets.make:6: all] Error 2
```

**Comment by jakobjakobson13** [comment]
Well, I'm struggleing with compiling texlive myself. Unfortunately, this seems not always very [trivial](http://ftp.math.utah.edu/pub/texlive-utah/).
I'm really sorry I can't help you.

**Pull request merged**
